project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
    toc-expand: 2
    fig-align: center
    lang: en-US
  pdf:
    toc: true
    papersize: A4
    fig-align: center
    lang: en-US
    pdf-engine: xelatex 
